learning_doc/learning_log/urls.py
from django.conf.urls import url ,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('learning_logs.urls',namespace='learning_logs')),   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_doc/learning_logs/urls.py
from django.conf.urls import url
from . import views
#FIXME :别忘记.表示当前目录

urlpatterns=[
    #FIXME :r'^$'表示空字符串
    url(r'^index/$',views.index,name='index'),
    #实现多级路由 localhost:8000/fir/helloworld
    url(r'^helloworld/$',views.hello_world,name='hello_world'),
    
    url(r'^topics/(?P<writer_name>\w+)/$',views.topics,name='topics'),
    #TODO： :r'^$'表示空字符串
    # 不可以多级别吗？
    url(r'^topics/(?P<viewer_name>\w+)/(?P<topic_id>\d+)/(?P<sort_type>\w+)/$',views.topic,name='topic'),
    
    url(r'^new_entry/(?P<writer_name>\w+)/(?P<topic_id>\d+)/$',views.new_entry,name='new_entry'),
   
    url(r'^new_topic/(?P<writer_name>\w+)/$',views.new_topic,name='new_topic'),
    
    url(r'^login/$',views.login,name='login'),
    
    url(r'^$',views.login,name='login'),
    
    
    url(r'^register/$',views.register,name='register'),
        
    url(r'^base/(?P<writer_name>\w+)$',views.base,name='base'),


    url(r'^profile/(?P<writer_name>\w+)/$',views.profile,name='profile'),

    url(r'^forum/(?P<viewer_name>\w+)/(?P<order_type>\w+)/$',views.forum,name='forum'),

    url(r'^toggle_favorite/(?P<viewer_name>\w+)/(?P<topic_id>\d+)/(?P<page_type>\w+)/$',views.toggle_favorite,name='toggle_favorite'),


    url(r'^my_favor/(?P<viewer_name>\w+)/(?P<order_type>\w+)/$',views.my_favor,name='my_favor'),

    url(r'^topic_writer_profile/(?P<viewer_name>\w+)/(?P<topic_id>\d+)/$',views.topic_writer_profile,name='topic_writer_profile'),

]

learning_doc/learning_logs/models.py
from django.db import models


class Register_Writer(models.Model):
    name=models.CharField(max_length=200,default=" ")
    password=models.CharField(max_length=200,default=" ")
    repassword=models.CharField(max_length=200,default=" ")
    telephone=models.CharField(max_length=200,default=" ")
    email=models.CharField(max_length=200,default=" ")
    instroduction=models.TextField(default=" ")
    avatar=models.ImageField(upload_to='user_images',default='user_images/default.jpg',max_length=200)
    def __str__(self):
        return self.name


class Writer(models.Model):
    name=models.CharField(max_length=200,default="")
    password=models.CharField(max_length=200,default="")
    repassword = models.CharField(max_length=200,default="")
    telephone=models.CharField(max_length=200,default="")
    email=models.CharField(max_length=200,default="")
    instroduction=models.TextField(default="")
    avatar=models.ImageField(upload_to='user_images',default='user_images/default.jpg',max_length=200)

    def __str__(self):
        return self.name


class Image(models.Model):
    image_name=models.CharField(max_length=200,default="")
    image=models.ImageField(upload_to='images',null=True,max_length=200)
class Topic(models.Model):
    writer = models.ForeignKey(Writer, on_delete=models.CASCADE, null=True,related_name='topics')
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
        if self.writer is None:
            self.writer = Writer.get_default_writer()
        super().save(*args, **kwargs)


# 条目
class Entry(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE,related_name='entries')
    text = models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
#FIXME：没有理解Meta的用法
    class Meta: 
        verbose_name_plural='entries'
    
    def __str__(self):
        return self.text[:50]+"..."
    
class Favorite(models.Model):
    lover=models.ForeignKey(Writer,on_delete=models.CASCADE,related_name='lovers')
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE,related_name='favor_topics')
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.topic.text[:50]+"..."

learning_doc/learning_logs/views.py
from django.shortcuts import render
from .models import Topic,Entry,Writer,Image,Favorite
from .froms import TopicForm,EntryFrom,WriterForm,RegisterForm,LoginForm
from django.http import HttpResponseRedirect,Http404
from django.core.urlresolvers import reverse
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.db.models import Count
from django.http import HttpResponse
import os
# Create your views here.

def index(request):
    """学习笔记的主页"""
    return render(request,'learning_logs/index.html')


def hello_world(request):
    return render(request,'learning_logs/hello_world.html')


def topics(request,writer_name):
    curr_writer=Writer.objects.filter(name=writer_name).first()
    topics=curr_writer.topics.order_by('date_added')
    print("topics:"+str(topics))
    context={'writer_name':writer_name,'topics':topics}   
    return render(request,'learning_logs/topics.html',context)

def topic(request,viewer_name,topic_id,sort_type):
    topic = Topic.objects.get(id=topic_id)
    viewer=Writer.objects.filter(name=viewer_name).first()
    entries=topic.entries.order_by('-date_added')
    favor=topic.favor_topics.filter(lover=viewer).first()
    favor_num=topic.favor_topics.count()
    is_favor=True
    if favor is None:
        is_favor=False
    context={'viewer_name':viewer_name,'topic':topic,'entries':entries,"is_favor":is_favor,
             "favor_num":favor_num,"sort_type":sort_type}
    print("viewer_name:"+viewer_name)
    return render(request,'learning_logs/topic.html',context)


def new_topic(request,writer_name):
    if request.method!='POST':
        form=TopicForm()
    else:
        form=TopicForm(request.POST)
        if form.is_valid():
            data=form.save(commit=False)    
            
            writer=Writer.objects.filter(name=writer_name).first()
            data.writer=writer
            data.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[writer_name,data.id,'new']))
    context={'form':form , 'writer_name':writer_name}
    return render(request,'learning_logs/new_topic.html',context)


def login(request):
    msg=""
    if request.method!='POST':
        form=LoginForm()
    else:
        form=LoginForm(request.POST)
        if form.is_valid():
            data=form.save(commit=False)
            data_in_db=Writer.objects.filter(name=data.name).first()
            #TODO:这里跳转到一个新的页面，再跳回来，实现错误处理
            if data_in_db is None:
                msg="用户名不存在,请重新输入"
            elif data_in_db.password!=data.password:
                msg="密码错误,请重新输入"
            elif data_in_db.password==data.password:
                 return HttpResponseRedirect(reverse('learning_logs:profile',args=[data_in_db.name]))
    context={'form':form,'msg':msg}
    return render(request,'learning_logs/login.html',context)


def register(request):
    msg=""

    #预先存贮的头像图片
    try:
        default_avatar = Image.objects.get(id=1)
        print("default_avatar is exist")
    except ObjectDoesNotExist:
        print("default_avatar not exist")
        default_avatar = None
    if request.method!='POST':
        form=WriterForm()
    else:
        form=WriterForm(request.POST, request.FILES)
        if form.is_valid():
            data=form.save(commit=False)
            data_in_db=Writer.objects.filter(name=data.name).first()
            if data.password!=data.repassword:
                msg="两次密码不一致,请重新输入"
            elif data_in_db is not None:
                msg="用户名已存在,请重新输入"
            elif data.password==data.repassword:
                 #处理图片

                 new_writer=form.save()
                 instructions=Topic(writer=new_writer,text="你好{}，这是我们为你准备的使用说明".format(new_writer.name))
                 instructions.save()

                 instr_entry=Entry(topic=instructions,text=
                                   "你好{},欢迎使用学习笔记,在这里你可以创建你自己的文章,添加，编辑你的条目，还可以阅览其他用户创建的优秀文章，"
                                   "快来体验吧！".format(new_writer.name))
                 instr_entry.save()

                 return HttpResponseRedirect(reverse('learning_logs:profile',args=[new_writer.name]))
    context={'form':form,'msg':msg,'default_avatar':default_avatar}
    return render(request,'learning_logs/register.html',context)


def profile(request,writer_name):
    curr_writer=Writer.objects.filter(name=writer_name).first()
    context={'writer_name':writer_name,'writer':curr_writer}
    return render(request,'learning_logs/profile.html',context)

def base(request,writer_name):
    context={'writer_name':writer_name}
    return render(request,'learning_logs/base.html',context)

def new_entry(request,writer_name,topic_id):
    curr_writer=Writer.objects.filter(name=writer_name).first()
    topic=Topic.objects.get(writer=curr_writer,id=topic_id)
    if request.method!='POST':
        form=EntryFrom()
    else:
        form=EntryFrom(data=request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=Topic.objects.get(id=topic_id)
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[writer_name,topic_id,'new']))
    print("In func new_entry topic_id:"+str(topic_id))
    context={'form':form,'topic':topic,'writer_name':writer_name,}
    return render(request,'learning_logs/new_entry.html',context)

def forum(request,viewer_name,order_type='new'):
    me=Writer.objects.filter(name=viewer_name).first()
    print("me:"+str(me))
    sorted_topics=Topic.objects.exclude(writer=me).order_by('-date_added')
    for topic in sorted_topics:
        if "这是我们为你准备的使用说明" in topic.text:
            sorted_topics=sorted_topics.exclude(id=topic.id)
    if order_type=='hot':
        sorted_topics=sorted_topics.annotate(num_entries=Count('entries')).order_by('-num_entries')
    elif order_type=='favorite':
        sorted_topics=sorted_topics.annotate(num_favorites=Count('favor_topics')).order_by('-num_favorites')
    context={'viewer_name':viewer_name,'topics':sorted_topics,'order_type':order_type}
    return render(request,'learning_logs/forum.html',context)


def my_favor(request,viewer_name,order_type='new'):
    me=Writer.objects.filter(name=viewer_name).first()

    topics = me.lovers.all().values_list('topic', flat=True)
    #直接排序？
    sorted_topics=Topic.objects.filter(id__in=topics).order_by('-date_added')
    if order_type=='hot':
        sorted_topics=sorted_topics.annotate(num_entries=Count('entries')).order_by('-num_entries')
    elif order_type=='favorite':
        sorted_topics=sorted_topics.annotate(num_favorites=Count('favor_topics')).order_by('-num_favorites')
    context={'viewer_name':viewer_name,'topics':sorted_topics,'order_type':order_type}
    return render(request,'learning_logs/my_favor.html',context)

def toggle_favorite(request,viewer_name,topic_id,page_type='forum'):
    topic=Topic.objects.get(id=topic_id)
    me=Writer.objects.filter(name=viewer_name).first()
    new_favor=me.lovers.filter(lover=me,topic=topic)
    msg=""
    if new_favor:
        print("已经取消收藏")
        new_favor.delete()
        msg="已经取消收藏"
    else:
        print("已经收藏")
        my_new_favor=Favorite(lover=me,topic=topic)
        my_new_favor.save()
        msg="已经收藏"
    context={'viewer_name':viewer_name,'topic':topic,'msg':msg,'page_type':page_type}
    return render(request,'learning_logs/favor_msg.html',context)

def topic_writer_profile(request,viewer_name,topic_id):
    topic=Topic.objects.get(id=topic_id)
    writer=topic.writer
    topics=writer.topics.all()
    context={'viewer_name':viewer_name,'writer':writer,'topics':topics}
    return render(request,'learning_logs/topic_writer_profile.html',context)





learning_doc/learning_logs/templates/learning_logs/base.html
<p>欢迎来到学习笔记，亲爱的{{writer_name}}</p>
<p>
    <a href="{%url 'learning_logs:topics' writer_name %}">Topics</a>
    <a href="{%url 'learning_logs:login'%}">Logout</a>
</p>

learning_doc/learning_logs/templates/learning_logs/favor_msg.html
<p>{{msg}}</p>
{%if page_type == 'forum' %}
    <a href="{%url 'learning_logs:topic' viewer_name topic.id 'new' %}">返回</a>
{%elif page_type == 'my_favor' %}
    <a href="{%url 'learning_logs:my_favor' viewer_name 'new' %}">返回</a>
{%endif%}

learning_doc/learning_logs/templates/learning_logs/forum.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>forum</title>
     <style>
    .circle {
        border-radius: 50%;
        width: 50px;
        height: 50px;
        object-fit: cover;
    }
    </style>

</head>
<body>
  <p>欢迎来到学习笔记论坛板块，亲爱的{{viewer_name}}</p>
  <a href="{% url 'learning_logs:forum'  viewer_name 'hot' %}">按照热度查看</a><br>
  <a href="{% url 'learning_logs:forum'  viewer_name 'new' %}">按照日期查看 </a><br>
  <a href="{% url 'learning_logs:forum'  viewer_name 'favorite' %}">按照受喜欢程度查看 </a><br>
  <ul>
      {%for topic in topics%}
          <li>
            <img src="{{ topic.writer.avatar.url }}" alt="Avatar" class="circle">
            <a href="{% url 'learning_logs:topic'  viewer_name topic.id order_type %}" style="font-size: 40px;">{{topic}} </a>
              <p>来自于{{topic.writer.name}},上传日期{{topic.date_added}}</p>

          </li>
      {% empty %}
          <li>No topics have been added yet.</li>
      {% endfor %}
  </ul>
<a href="{%url 'learning_logs:profile' viewer_name %}">返回我的信息</a><br>
</body>
</html>

learning_doc/learning_logs/templates/learning_logs/hello_world.html
<p> hello django!<p>

learning_doc/learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{%block content%}

    <p>In learning log</p>

{%endblock content%}

learning_doc/learning_logs/templates/learning_logs/login.html
<p>Please login.</p>
<a href="{%url 'learning_logs:register'%}">还没有账户？立即注册！</a>
<p>{{msg}}</p>
<form action="{% url 'learning_logs:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">login</button>
</form>

learning_doc/learning_logs/templates/learning_logs/my_favor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>forum</title>
     <style>
    .circle {
        border-radius: 50%;
        width: 50px;
        height: 50px;
        object-fit: cover;
    }
    </style>

</head>
<body>
  <p>这里是{{viewer_name}}收藏的文章</p>
  <a href="{% url 'learning_logs:my_favor'  viewer_name 'hot' %}">按照热度查看</a><br>
  <a href="{% url 'learning_logs:my_favor'  viewer_name 'new' %}">按照日期查看 </a><br>
  <a href="{% url 'learning_logs:my_favor'  viewer_name 'favorite' %}">按照受喜欢程度查看 </a><br>
  <ul>
      {%for topic in topics%}
          <li>
            <img src="{{ topic.writer.avatar.url }}" alt="Avatar" class="circle">
            <a href="{% url 'learning_logs:topic'  viewer_name topic.id 'new' %}" style="font-size: 40px;">{{topic}} </a>
              <p>来自于{{topic.writer.name}},上传日期{{topic.date_added}}</p>
            <button name="submit"  onclick="window.location.href='{% url 'learning_logs:toggle_favorite' viewer_name topic.id 'my_favor' %}'">取消收藏</button>
          </li>
      {% empty %}
          <li>No topics have been added yet.</li>
      {% endfor %}
  </ul>
<a href="{%url 'learning_logs:profile' viewer_name %}">返回我的信息</a><br>
</body>
</html>

learning_doc/learning_logs/templates/learning_logs/new_entry.html
<p>欢迎来到学习笔记，亲爱的{{writer_name}}</p>
<a href="{% url 'learning_logs:topic'  writer_name topic.id 'new' %}">返回Topic:{{topic}}</a>
<p>Topics:{{topic}}</p>
<p>Greate a new entry</p>
<form action="{% url 'learning_logs:new_entry' topic.writer.name topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
</form>

learning_doc/learning_logs/templates/learning_logs/new_topic.html
<a href="{%url 'learning_logs:topics' writer_name %}">我的文章</a><br>
<p>欢迎来到学习笔记，亲爱的{{writer_name}}</p>
<p>Greate a new topic</p>
<form action="{% url 'learning_logs:new_topic' writer_name %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add topic</button>
</form>

learning_doc/learning_logs/templates/learning_logs/profile.html
<p>个人信息页面</p>
<style>
.circle {
    border-radius: 50%;
    width: 100px;
    height: 100px;
    object-fit: cover;
}
</style>

<img src="{{ writer.avatar.url }}" alt="Avatar" class="circle">
<p>用户名：{{writer.name}}</p>
<p>个人简介：{{writer.instroduction}}</p>
<p>邮箱：{{writer.email}}</p>

<a href="{%url 'learning_logs:topics' writer.name %}">我的文章</a><br>
<a href="{%url 'learning_logs:forum' writer.name 'new'%}">学习论坛</a>
<a href="{%url 'learning_logs:my_favor' writer.name 'new' %}">我的收藏</a><br>
<a href="{%url 'learning_logs:login'%}">退出登录</a>

learning_doc/learning_logs/templates/learning_logs/register.html
<style>
.circle {
    border-radius: 50%;
    width: 100px;
    height: 100px;
    object-fit: cover;
}
</style>
<p>Please Register
<a href="{%url 'learning_logs:login'%}">已经有账户？</a>
</p>
<img id="avatarPreview" src=" {{ default_avatar.image.url }} " alt="your image" style="max-width: 200px; max-height: 200px;" class="circle"/>
<form action="{% url 'learning_logs:register' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">register</button>
</form>
<script>
    document.querySelector('#id_avatar').addEventListener('change', function(e) {
        var file = e.target.files[0];
        var reader = new FileReader();
        reader.onloadend = function() {
            document.querySelector('#avatarPreview').src = reader.result;
        }
        if (file) {
            reader.readAsDataURL(file);
        } else {
            document.querySelector('#avatarPreview').src = "";
        }
    });
</script>

learning_doc/learning_logs/templates/learning_logs/topic.html
<p>欢迎来到学习笔记，亲爱的{{viewer_name}}</p>
{% if viewer_name == topic.writer.name %}
    <a href="{%url 'learning_logs:topics' viewer_name %}">我的文章</a><br>
    <a href="{%url 'learning_logs:profile' viewer_name %}">我的信息</a><br>
    <a href="{% url 'learning_logs:new_entry' viewer_name topic.id %}">Add a new entry</a>
    <p>你的这篇文章已经被{{favor_num}}个人收藏</p>
    <p>你可以查看下面文章</p>
{% else %}
    <p>在这里你可以查看作者{{topic.writer.name}}的文章，这篇文章已经被{{favor_num}}个人收藏</p>
    <a href="{%url 'learning_logs:topic_writer_profile' viewer_name topic.id %}">查看作者{{topic.writer.name}}的其他文章</a><br><br><br>
    {% if is_favor %}
        <button name="submit"  onclick="window.location.href='{% url 'learning_logs:toggle_favorite' viewer_name topic.id 'forum' %}'">取消收藏</button>
    {% else %}
        <button name="submit"  onclick="window.location.href='{% url 'learning_logs:toggle_favorite' viewer_name topic.id 'forum' %}'">收藏</button>
    {% endif %}
{% endif %}
<p>Topics:{{topic}}</p>

<ul>
    {%for entry in entries%}
        <li>
            <p>{{entry.date_added|date:'M d, Y H:i'}}</p>
            <p>{{entry.text|linebreaks}}</p>
        </li>
    {% empty %}
        <li>No entry have been added yet.</li>
    {% endfor %}
</ul>
<a href="{%url 'learning_logs:forum' viewer_name sort_type %}">学习论坛</a>
<a href="{%url 'learning_logs:login'%}">退出登录</a><br>

learning_doc/learning_logs/templates/learning_logs/topic_writer_profile.html
<p>作者{{writer.name}}信息页面</p>
<style>
.circle {
    border-radius: 50%;
    width: 100px;
    height: 100px;
    object-fit: cover;
}
</style>

<img src="{{ writer.avatar.url }}" alt="Avatar" class="circle">
<p>用户名：{{writer.name}}</p>
<p>个人简介：{{writer.instroduction}}</p>
<p>邮箱：{{writer.email}}</p>

{%for topic in topics%}
    <li> <a href="{% url 'learning_logs:topic'  viewer_name topic.id 'new' %}">{{topic}}</a>
    </li>
{% empty %}
    <li>No topics have been added yet.</li>
{% endfor %}
<br>
<a href="{%url 'learning_logs:forum' viewer_name 'new'%}">学习论坛</a>

learning_doc/learning_logs/templates/learning_logs/topics.html
<p>欢迎来到学习笔记，亲爱的{{writer_name}}</p>
<a href="{% url 'learning_logs:new_topic' writer_name %}">添加新Topic:</a><br>
<a href="{%url 'learning_logs:profile' writer_name %}">我的信息</a><br>
<a href="{%url 'learning_logs:forum' writer_name 'new'%}">学习论坛</a><br>
<a href="{%url 'learning_logs:login'%}">退出登录</a><br>
<p>Topics:</p>

<ul>
    {%for topic in topics%}
        <li> <a href="{% url 'learning_logs:topic'  writer_name topic.id 'new'%}">{{topic}}</a>
        </li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
